---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-server
  labels:
    app: helm-server
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list, watch]
- apiGroups: [apiregistration.k8s.io]
  resources: [apiservices]
  verbs: [get, list, watch]
- apiGroups: [token.accordions.co.kr]
  resources: [multiclustertokenrequests]
  verbs: [create]
- apiGroups: [management.accordions.co.kr]
  resources: [clusterinfoes]
  verbs: [get, list, watch]
