---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-server-config
  namespace: acc-global
  labels:
    app: helm-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: accordion-storage
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-server-cache
  namespace: acc-global
  labels:
    app: helm-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: accordion-storage
  volumeMode: Filesystem
