---
apiVersion: v1
kind: Secret
metadata:
  name: gateway
  namespace: acc-global
  labels:
    app: gateway
stringData:
  keycloak-access-mode: blocklist
  keycloak-access-addresses: ""
  session-key: ""
