---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gateway
  labels:
    app: gateway
    version: 2.0.6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway
subjects:
- kind: ServiceAccount
  name: gateway
  namespace: acc-global
