---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: acc-global
  labels:
    app: gateway
    version: 2.0.6
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
