---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
  namespace: acc-global
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      imagePullSecrets:
        - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
        - image: "{{ base_registry_address }}:{{ base_registry_port }}/console:{{ console_version }}"
          imagePullPolicy: Always
          name: webserver
      restartPolicy: Always
