---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-apiserver-rolebinding
  namespace: acc-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cicd-apiserver-role
subjects:
- kind: ServiceAccount
  name: cicd-apiserver
  namespace: acc-system
