---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-apiserver-role
  namespace: acc-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
