kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-server
  labels:
    app: cluster-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-server
subjects:
- kind: ServiceAccount
  name: cluster-server
  namespace: acc-global

