---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.token.accordions.co.kr
  labels:
    app: cluster-server
spec:
  group: token.accordions.co.kr
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: cluster-server
    namespace: acc-global
    port: 8443
  version: v1beta1
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.activator.accordions.co.kr
  labels:
    app: cluster-server
spec:
  group: activator.accordions.co.kr
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: cluster-server
    namespace: acc-global
    port: 8443
  version: v1beta1
  versionPriority: 100
