apiVersion: v1
kind: Service
metadata:
  name: cicd-trigger-webhook-service
  namespace: acc-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: cicd-trigger-manager
