apiVersion: v1
data:
  ca.crt: {{ base_ca_crt.stdout }}
  tls.crt: {{ base_trigger_tls_crt.stdout }}
  tls.key: {{ base_trigger_tls_key.stdout }}
kind: Secret
metadata:
  name: cicd-trigger-webhook-server-cert
  namespace: acc-system
type: kubernetes.io/tls
