---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: monitoring-apiserver
rules:
- apiGroups: ["management.accordions.co.kr"]
  resources: ["clusterinfoes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: [configmaps]
  verbs: [get]
