---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-proxy
  namespace: acc-global
  labels:
    app: gateway-proxy
type: kubernetes.io/tls
data:
  tls.crt: "{{ base_tls_crt.stdout }}"
  tls.key: "{{ base_tls_key.stdout }}"
