---
apiVersion: v1
kind: Service
metadata:
  name: gateway-proxy
  namespace: acc-global
  labels:
    app: gateway-proxy
spec:
  externalTrafficPolicy: Local
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30000
  type: NodePort
  selector:
    app: gateway-proxy
