---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-egressgateway-service-account
  namespace: acc-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingressgateway-service-account
  namespace: acc-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-reader-service-account
  namespace: acc-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod
  namespace: acc-system

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod-service-account
  namespace: acc-system