apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    release-name: chartmuseum
    release-namespace: acc-global
  generation: 1
  labels:
    app: chartmuseum
    release: chartmuseum
  name: chartmuseum-chartmuseum
  namespace: acc-global
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chartmuseum
      release: chartmuseum
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chartmuseum
        release: chartmuseum
      name: chartmuseum-chartmuseum
    spec:
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
      - args:
        - --port=8080
        - --storage-local-rootdir=/storage
        env:
        - name: CHART_POST_FORM_FIELD_NAME
          value: chart
        - name: CONTEXT_PATH
          value: /charts
        - name: DISABLE_METRICS
          value: "true"
        - name: LOG_JSON
          value: "true"
        - name: PROV_POST_FORM_FIELD_NAME
          value: prov
        - name: STORAGE
          value: local
#        - name: BASIC_AUTH_PASS
#          valueFrom:
#            secretKeyRef:
#              key: BASIC_AUTH_PASS
#              name: chartmuseum-chartmuseum
#        - name: BASIC_AUTH_USER
#          valueFrom:
#            secretKeyRef:
#              key: BASIC_AUTH_USER
#              name: chartmuseum-chartmuseum
        image: {{ base_registry_address }}:{{ base_registry_port }}/chartmuseum:v0.12.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /charts/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: chartmuseum
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /charts/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /storage
          name: storage-volume
          subPath: storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: chartmuseum-chartmuseum
