apiVersion: v1
kind: Secret
metadata:
  annotations:
    release-name: chartmuseum
    release-namespace: acc-global
  labels:
    app: chartmuseum
    release: chartmuseum
  name: chartmuseum-chartmuseum
  namespace: acc-global
stringData:
  BASIC_AUTH_USER: {{ chart_id }}
  BASIC_AUTH_PASS: {{ chart_pw }}
