apiVersion: v1
kind: Service
metadata:
  annotations:
    release-name: chartmuseum
    release-namespace: acc-global
  labels:
    app: chartmuseum
    release: chartmuseum
  name: chartmuseum-chartmuseum
  namespace: acc-global
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: chartmuseum
    release: chartmuseum
  sessionAffinity: None
  type: ClusterIP
