---
apiVersion: v1
kind: Secret
metadata:
  name: registry-webhook-server-cert
  namespace: acc-system
data:
  ca.crt: {{ base_registry_ca_crt.stdout }}
  tls.crt: {{ base_registry_tls_crt.stdout }}
  tls.key: {{ base_registry_tls_key.stdout }}
type: kubernetes.io/tls
