---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry-manager
  name: registry-manager
  namespace: acc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-manager
  template:
    metadata:
      labels:
        app: registry-manager
    spec:
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
      - command:
        - /registry-manager
        image: "{{ base_registry_address }}:{{ base_registry_port }}/registry-manager:{{ registry_manager_version }}"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
          readOnly: true
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsUser: 65532
      serviceAccountName: registry-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /etc/localtime
        name: timezone
      - name: cert
        secret:
          defaultMode: 420
          secretName: registry-webhook-server-cert
