apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db
  namespace: acc-global
  labels:
    app: keycloak-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "{{ keycloak_storage }}"
  storageClassName: accordion-storage
  volumeMode: Filesystem

