---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: acc-global
  labels:
    app: keycloak-db
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "accordion!@#"
