---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-db
  namespace: acc-global
  labels:
    app: keycloak-db
spec:
  clusterIP: "{{ service_ip.stdout }}.1.13"
  selector:
    app: keycloak-db
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
