---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cicd-impersonator-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - impersonate
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
