---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cicd-workspace-pvc-provider-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cicd-workspace-pvc-provider-role
subjects:
- kind: ServiceAccount
  name: cicd-manager
  namespace: acc-system
