---
apiVersion: v1
data:
  ca.crt: {{ base_registry_ca_crt.stdout }}
  tls.crt: {{ base_registry_tls_crt.stdout }}
  tls.key: {{ base_registry_tls_key.stdout }}
kind: Secret
metadata:
  name: cicd-webhook-server-cert
  namespace: acc-system
type: kubernetes.io/tls

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-cred
  namespace: acc-system
data:
  accesskey: bWluaW8=
  secretkey: bWluaW8xMjM=

