---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: acc-system
data:
  config.json: |-
    [
      {
        "clusterID": "{{ ceph_fsid }}",
        "monitors": [
          "{{ ceph_server_ip }}:{{ ceph_server_port }}"
        ]
      }
    ]

