---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: acc-system
stringData:
  userID: {{ ceph_id }}
  userKey: {{ ceph_key }}

  # Encryption passphrase
  encryptionPassphrase: test_passphrase
