---
apiVersion: v1
kind: Service
metadata:
  name: manual-webserver
  namespace: acc-global
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: manual-webserver
  type: ClusterIP

