---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cicd-template-sync-manager-role
rules:
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - catalogtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - clustercatalogtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - clusterpipelinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - clustertasktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - multiclustercatalogtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - multiclusterpipelinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - multiclustertasktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - pipelinetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cicd.accordions.co.kr
  resources:
  - tasktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.accordions.co.kr
  resources:
  - clusterinfoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - token.accordions.co.kr
  resources:
  - multiclustertokenrequests
  verbs:
  - create
