apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cicd-template-sync-manager
  name: cicd-template-sync-manager
  namespace: acc-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-template-sync-manager
  template:
    metadata:
      labels:
        app: cicd-template-sync-manager
    spec:
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
      - command:
        - /cicd-template-sync-manager
        image: "{{ base_registry_address }}:{{ base_registry_port }}/cicd-template-sync-manager:{{ cicd_template_sync_manager_version }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone
          readOnly: true
      securityContext:
        runAsUser: 65532
      serviceAccountName: cicd-template-sync-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /etc/localtime
        name: timezone
