---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-template-sync-leader-election-role
  namespace: acc-system
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - endpoints
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
