---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-template-sync-manager-config
  namespace: acc-system
data:
  config: |
    log:
      encoder: console
      level: 0 # (ERROR: -1, INFO: 0, DEBUG: 1, DEBUG Detail : 1 over)
    excludeNamespaces:
      - kube-system
      - kube-public
      - acc-global
      - acc-system
