---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: accordion-storage
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "{{ ceph_fsid }}"
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: acc-system
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: acc-system
  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: acc-system
  fsName: "{{ ceph_fsname }}"
allowVolumeExpansion: true
mountOptions:
- nolock
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
