---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  alert-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alert-apiserver
subjects:
  - kind: ServiceAccount
    name:  alert-apiserver
    namespace: acc-global

