---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alert-apiserver
rules:
- apiGroups: ["management.accordions.co.kr"]
  resources: ["clusterinfoes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["*"]
