---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-event-exporter
  namespace: acc-system
  labels:
    app: kube-event-exporter
data:
  config.yaml: |
    route:
      routes:
        - match:
          - receiver: elasticsearch-dump
    receivers:
      - name: "elasticsearch-dump"
        elasticsearch:
          hosts:
          - http://opensearch-cluster-master.acc-system:9200
          index: acc-event
          indexFormat: "acc-event-{2006-01-02}"
          deDot: true
