apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-event-exporter
  labels:
    app: kube-event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-event-exporter
subjects:
  - kind: ServiceAccount
    namespace: acc-system
    name: kube-event-exporter

