---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acc-system
  name: kube-event-exporter
  labels:
    app: kube-event-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-event-exporter
  template:
    metadata:
      labels:
        app: kube-event-exporter
    spec:
      serviceAccountName: kube-event-exporter
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
        - name: kube-event-exporter
          image: "{{ base_registry_address }}:{{ base_registry_port }}/kubernetes-event-exporter:{{ kubernetes_event_exporter_version }}"
          imagePullPolicy: Always
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: config
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kube-event-exporter
        - name: timezone
          hostPath:
            type: ""
            path: /etc/localtime
