---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xlog-apiserver
  labels:
    app: xlog-apiserver
rules:
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - namespaces
  - services
  - deployments
  - pods
  - statefulsets
  verbs:
  - get
  - list

