apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    release-name: tsdb
    release-namespace: acc-system
  labels:
    app: tsdb-timescaledb
    cluster-name: tsdb
    release: tsdb
  name: tsdb-timescaledb
  namespace: acc-system
spec:
  podManagementPolicy: OrderedReady
{% if tsdb_ha == "yes" %}
  replicas: 2
{% else %}
  replicas: 1
{% endif %}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tsdb-timescaledb
      release: tsdb
  serviceName: tsdb-timescaledb
  template:
    metadata:
      labels:
        app: tsdb-timescaledb
        cluster-name: tsdb
        release: tsdb
      name: tsdb-timescaledb
    spec:
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
{% if tsdb_ha == "yes" %}
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: tsdb-timescaledb
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
{% endif %}
      containers:
      - command:
        - /bin/bash
        - -c
        - |2

          install -o postgres -g postgres -d -m 0700 "/var/lib/postgresql/data" "/var/lib/postgresql/wal/pg_wal" || exit 1
          TABLESPACES=""
          for tablespace in ; do
            install -o postgres -g postgres -d -m 0700 "/var/lib/postgresql/tablespaces/${tablespace}/data"
          done

          # Environment variables can be read by regular users of PostgreSQL. Especially in a Kubernetes
          # context it is likely that some secrets are part of those variables.
          # To ensure we expose as little as possible to the underlying PostgreSQL instance, we have a list
          # of allowed environment variable patterns to retain.
          #
          # We need the KUBERNETES_ environment variables for the native Kubernetes support of Patroni to work.
          #
          # NB: Patroni will remove all PATRONI_.* environment variables before starting PostgreSQL

          # We store the current environment, as initscripts, callbacks, archive_commands etc. may require
          # to have the environment available to them
          set -o posix
          export -p > "${HOME}/.pod_environment"
          export -p | grep PGBACKREST > "${HOME}/.pgbackrest_environment"

          for UNKNOWNVAR in $(env | awk -F '=' '!/^(PATRONI_.*|HOME|PGDATA|PGHOST|LC_.*|LANG|PATH|KUBERNETES_SERVICE_.*)=/ {print $1}')
          do
              unset "${UNKNOWNVAR}"
          done

          touch /var/run/postgresql/timescaledb.conf
          touch /var/run/postgresql/wal_status

          echo "*:*:*:postgres:${PATRONI_SUPERUSER_PASSWORD}" >> ${HOME}/.pgpass
          chmod 0600 ${HOME}/.pgpass

          export PATRONI_POSTGRESQL_PGPASS="${HOME}/.pgpass.patroni"

          exec patroni /etc/timescaledb/patroni.yaml
        env:
        - name: PATRONI_admin_OPTIONS
          value: createrole,createdb
        - name: PATRONI_REPLICATION_USERNAME
          value: standby
        - name: PATRONI_KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PATRONI_POSTGRESQL_CONNECT_ADDRESS
          value: $(PATRONI_KUBERNETES_POD_IP):5432
        - name: PATRONI_RESTAPI_CONNECT_ADDRESS
          value: $(PATRONI_KUBERNETES_POD_IP):8008
        - name: PATRONI_KUBERNETES_PORTS
          value: '[{"name": "postgresql", "port": 5432}]'
        - name: PATRONI_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: PATRONI_POSTGRESQL_DATA_DIR
          value: /var/lib/postgresql/data
        - name: PATRONI_KUBERNETES_NAMESPACE
          value: acc-system
        - name: PATRONI_KUBERNETES_LABELS
          value: '{app: tsdb-timescaledb, cluster-name: tsdb, release: tsdb}'
        - name: PATRONI_SCOPE
          value: tsdb
        - name: PGBACKREST_CONFIG
          value: /etc/pgbackrest/pgbackrest.conf
        - name: PGDATA
          value: $(PATRONI_POSTGRESQL_DATA_DIR)
        - name: PGHOST
          value: /var/run/postgresql
        - name: BOOTSTRAP_FROM_BACKUP
          value: "0"
        envFrom:
        - secretRef:
            name: tsdb-credentials
            optional: false
        - secretRef:
            name: tsdb-pgbackrest
            optional: true
        image: {{ base_registry_address }}:{{ base_registry_port }}/timescaledb-ha:pg12-ts2.5-latest
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - psql
              - -X
              - --file
              - /etc/timescaledb/scripts/lifecycle_preStop.psql
        name: timescaledb
        ports:
        - containerPort: 8008
          name: patroni
          protocol: TCP
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - /var/run/postgresql
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources: 
          limits:
            memory: 4Gi
          requests:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: storage-volume
          subPath: storage
        - mountPath: /var/lib/postgresql/wal
          name: wal-volume
          subPath: wal
        - mountPath: /etc/timescaledb/patroni.yaml
          name: patroni-config
          readOnly: true
          subPath: patroni.yaml
        - mountPath: /etc/timescaledb/scripts
          name: timescaledb-scripts
          readOnly: true
        - mountPath: /etc/timescaledb/post_init.d
          name: post-init
          readOnly: true
        - mountPath: /etc/certificate
          name: certificate
          readOnly: true
        - mountPath: /var/run/postgresql
          name: socket-directory
        - mountPath: /etc/pgbackrest
          name: pgbackrest
          readOnly: true
        - mountPath: /etc/pgbackrest/bootstrap
          name: pgbackrest-bootstrap
          readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - |
          set -e
          [ $CPUS -eq 0 ]   && CPUS="${RESOURCES_CPU_LIMIT}"
          [ $MEMORY -eq 0 ] && MEMORY="${RESOURCES_MEMORY_LIMIT}"

          if [ -f "${PGDATA}/postgresql.base.conf" ] && ! grep "${INCLUDE_DIRECTIVE}" postgresql.base.conf -qxF; then
            echo "${INCLUDE_DIRECTIVE}" >> "${PGDATA}/postgresql.base.conf"
          fi

          touch "${TSTUNE_FILE}"
          timescaledb-tune -quiet -pg-version 11 -conf-path "${TSTUNE_FILE}" -cpus "${CPUS}" -memory "${MEMORY}MB" \
             -yes

          # If there is a dedicated WAL Volume, we want to set max_wal_size to 60% of that volume
          # If there isn't a dedicated WAL Volume, we set it to 20% of the data volume
          if [ "${RESOURCES_WAL_VOLUME}" = "0" ]; then
            WALMAX="${RESOURCES_DATA_VOLUME}"
            WALPERCENT=20
          else
            WALMAX="${RESOURCES_WAL_VOLUME}"
            WALPERCENT=60
          fi

          WALMAX=$(numfmt --from=auto ${WALMAX})

          # Wal segments are 16MB in size, in this way we get a "nice" number of the nearest
          # 16MB
          WALMAX=$(( $WALMAX / 100 * $WALPERCENT / 16777216 * 16 ))
          WALMIN=$(( $WALMAX / 2 ))

          echo "max_wal_size=${WALMAX}MB" >> "${TSTUNE_FILE}"
          echo "min_wal_size=${WALMIN}MB" >> "${TSTUNE_FILE}"
        env:
        - name: TSTUNE_FILE
          value: /var/run/postgresql/timescaledb.conf
        - name: RESOURCES_WAL_VOLUME
          value: 1Gi
        - name: RESOURCES_DATA_VOLUME
          value: 2Gi
        - name: INCLUDE_DIRECTIVE
          value: include_if_exists = '/var/run/postgresql/timescaledb.conf'
        - name: CPUS
          valueFrom:
            resourceFieldRef:
              containerName: timescaledb
              divisor: "1"
              resource: requests.cpu
        - name: MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: timescaledb
              divisor: 1Mi
              resource: requests.memory
        - name: RESOURCES_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: timescaledb
              divisor: "1"
              resource: limits.cpu
        - name: RESOURCES_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: timescaledb
              divisor: 1Mi
              resource: limits.memory
        image: {{ base_registry_address }}:{{ base_registry_port }}/timescaledb-ha:pg12-ts2.5-latest
        imagePullPolicy: Always
        name: tstune
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/postgresql
          name: socket-directory
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: tsdb-timescaledb
      serviceAccountName: tsdb-timescaledb
      terminationGracePeriodSeconds: 600
      volumes:
      - emptyDir: {}
        name: socket-directory
      - configMap:
          defaultMode: 420
          name: tsdb-timescaledb-patroni
        name: patroni-config
      - configMap:
          defaultMode: 488
          name: tsdb-timescaledb-scripts
        name: timescaledb-scripts
      - name: post-init
        projected:
          defaultMode: 488
          sources:
          - configMap:
              name: custom-init-scripts
              optional: true
          - secret:
              name: custom-secret-scripts
              optional: true
      - configMap:
          defaultMode: 416
          name: tsdb-timescaledb-pgbouncer
          optional: true
        name: pgbouncer
      - configMap:
          defaultMode: 416
          name: tsdb-timescaledb-pgbackrest
          optional: true
        name: pgbackrest
      - name: certificate
        secret:
          defaultMode: 416
          secretName: tsdb-certificate
      - name: pgbackrest-bootstrap
        secret:
          defaultMode: 420
          optional: true
          secretName: pgbackrest-bootstrap
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: tsdb-timescaledb
        cluster-name: tsdb
        heritage: Helm
        purpose: data-directory
        release: tsdb
      name: storage-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ tsdb_storage }}
      storageClassName: accordion-storage
      volumeMode: Filesystem
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: tsdb-timescaledb
        cluster-name: tsdb
        heritage: Helm
        purpose: wal-directory
        release: tsdb
      name: wal-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ tsdb_wal_storage }}
      storageClassName: accordion-storage
      volumeMode: Filesystem
