---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: acc-global
  labels:
    app: keycloak
spec:
  clusterIP: "{{ service_ip.stdout }}.1.14"
  selector:
    app: keycloak
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
