---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: acc-global
  labels:
    app: keycloak
stringData:
  PROXY_ADDRESS_FORWARDING: "true"
  DB_VENDOR: postgres
  DB_ADDR: keycloak-db.acc-global
  DB_PORT: "5432"
  DB_DATABASE: keycloak
  DB_USER: admin
  DB_PASSWORD: "accordion!@#"
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: "accordion!@#$"
  KEYCLOAK_IMPORT: /tmp/realm.json
  JAVA_OPTS: >
    -server
    -Xms1024m
    -Xmx1024m
    -XX:MaxMetaspaceSize=256m
    -Djboss.modules.system.pkgs=org.jboss.byteman
    -Djava.net.preferIPv4Stack=true
    -Djava.awt.headless=true
    -Dkeycloak.profile=preview
    -Dkeycloak.profile.feature.token_exchange=enabled
  TZ: Asia/Seoul
  realm.json: |
    {
      "id": "accordion",
      "realm": "accordion",
      "enabled": true,
      "sslRequired": "none",
      "loginWithEmailAllowed": false,
      "loginTheme": "accordion.v2.0.0",
      "eventsEnabled": true,
      "eventsListeners": ["jboss-logging"],
      "enabledEventTypes": ["LOGOUT", "LOGIN"],
      "accessTokenLifespan": 1800,
      "ssoSessionIdleTimeout": 3600,
      "passwordPolicy": "length(8) and lowerCase(1) and specialChars(1) and regexPattern(^(?=.*[a-z])(?=.*[!@#$%^&*])[A-Za-z0-9!@#$%^&*]{8,16}$)",
      "users": [
        {
          "username": "service-account-accordion",
          "enabled": true,
          "serviceAccountClientId": "accordion",
          "clientRoles": {
            "realm-management": ["realm-admin"]
          }
        },
        {
          "username": "admin",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "Pa$$word",
              "temporary": true
            }
          ],
          "requiredActions": ["UPDATE_PASSWORD"]
        }
      ],
      "clients": [
        {
          "clientId": "accordion",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "secret": "{{ keycloak_secret.stdout }}",
          "redirectUris": ["*"],
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "protocolMappers": [
            {
              "name": "groups",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-group-membership-mapper",
              "consentRequired": false,
              "config": {
                "full.path": "false",
                "id.token.claim": "true",
                "access.token.claim": "true",
                "claim.name": "groups",
                "userinfo.token.claim": "true"
              }
            }
          ]
        }
      ],
      "internationalizationEnabled": true,
      "supportedLocales": ["ko"],
      "defaultLocale": "ko"
    }
