---
- name: Join nodes with manager-master
  shell: "kubeadm join --token {{ hostvars[groups['manager-master'][0]].token.stdout }} {{ keep_vip }}:{{ haproxy_port }} --ignore-preflight-errors=all --discovery-token-unsafe-skip-ca-verification"
  register: kubeadm_join_command
  tags:
    - output
