apiVersion: v1
data:
  CACHE_REDIS_PASSWORD: ""
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-chartmuseum
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  CSRF_KEY: a09QR0JhSW9iR0xHdk5kejYxWGtiVGJ3T25oVTV3RUU=
  HARBOR_ADMIN_PASSWORD: {{ base_random_passwd.stdout }}
  POSTGRESQL_PASSWORD: Y2hhbmdlaXQ=
  REGISTRY_CREDENTIAL_PASSWORD: {{ base_random_passwd.stdout }}
  secret: amVSM1Z6c0VqWm1vZHFMMQ==
  secretKey: bm90LWEtc2VjdXJlLWtleQ==
  tls.crt: {{ base_core_tls_crt.stdout }}
  tls.key: {{ base_core_tls_key.stdout }}
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-core
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  POSTGRES_PASSWORD: Y2hhbmdlaXQ=
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-database
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  JOBSERVICE_SECRET: dDV0dVViM0tYRVgxV0RjTQ==
  REGISTRY_CREDENTIAL_PASSWORD: {{ base_random_passwd.stdout }}
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-jobservice
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  ca.crt: {{ base_ca_crt.stdout }}
  tls.crt: {{ base_tls_crt.stdout }}
  tls.key: {{ base_tls_key.stdout }}
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-nginx
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  ca.crt: {{ base_ca_crt.stdout }}
  server.json: {{ base_server_json.stdout }} 
  signer.json: ewogICJzZXJ2ZXIiOiB7CiAgICAiZ3JwY19hZGRyIjogIjo3ODk5IiwKICAgICJ0bHNfY2VydF9maWxlIjogIi9ldGMvc3NsL25vdGFyeS90bHMuY3J0IiwKICAgICJ0bHNfa2V5X2ZpbGUiOiAiL2V0Yy9zc2wvbm90YXJ5L3Rscy5rZXkiCiAgfSwKICAibG9nZ2luZyI6IHsKICAgICJsZXZlbCI6ICJpbmZvIgogIH0sCiAgInN0b3JhZ2UiOiB7CiAgICAiYmFja2VuZCI6ICJwb3N0Z3JlcyIsCiAgICAiZGJfdXJsIjogInBvc3RncmVzOi8vcG9zdGdyZXM6Y2hhbmdlaXRAaGFyYm9yLWRhdGFiYXNlOjU0MzIvbm90YXJ5c2lnbmVyP3NzbG1vZGU9ZGlzYWJsZSIsCiAgICAiZGVmYXVsdF9hbGlhcyI6ICJkZWZhdWx0YWxpYXMiCiAgfQp9
  tls.crt: {{ base_core_tls_crt.stdout }}
  tls.key: {{ base_core_tls_key.stdout }}
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    component: notary
    release: harbor
  name: harbor-notary-server
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  REGISTRY_HTPASSWD: {{ base_htpasswd.stdout }}
  REGISTRY_HTTP_SECRET: bmpTeFJRcldGZHh6MkU0Mg==
  REGISTRY_REDIS_PASSWORD: ""
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-registry
  namespace: acc-system
type: Opaque

---
apiVersion: v1
data:
  gitHubToken: ""
  redisURL: cmVkaXM6Ly9oYXJib3ItcmVkaXM6NjM3OS81P2lkbGVfdGltZW91dF9zZWNvbmRzPTMw
kind: Secret
metadata:
  annotations:
    release-name: harbor
    release-namespace: acc-system
  labels:
    app: harbor
    release: harbor
  name: harbor-trivy
  namespace: acc-system
type: Opaque
