---
apiVersion: cicd.accordions.co.kr/v1beta1
kind: ClusterCatalogSnippet
metadata:
  annotations:
    accordions.co.kr/description: https://kubernetes.io/docs/concepts/configuration/secret
    accordions.co.kr/summary: Kubernetes Secret
  name: secret
spec:
  resource: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: {{{.CATALOG.NAME}}}
    {{- if eq .values.secret.type "Opaque"}}
    type: Opaque
    data:
    {{- range $i, $e := .values.secret.data}}
      {{$e.key}}: {{b64enc $e.value}}
    {{- end}}
    {{- else if eq .values.secret.type "kubernetes.io/dockerconfigjson"}}
    type: kubernetes.io/dockerconfigjson
    data:
      {{- $server := .values.secret.server}}
      {{- $username := .values.secret.username}}
      {{- $password := .values.secret.password}}
      {{- $dockerauth := b64enc $username ":" $password}}
      {{- $dockerconfigjson := b64enc (print "{\"auths\":{\"" $server "\":{\"username\":\"" $username "\",\"password\":\"" $password "\",\"auth\":\"" $dockerauth "\"}}}")}}
      .dockerconfigjson: {{$dockerconfigjson}}
    {{- else if eq .values.secret.type "kubernetes.io/basic-auth"}}
    type: kubernetes.io/basic-auth
    data:
      username: {{b64enc .values.secret.username}}
      password: {{b64enc .values.secret.password}}
    {{- else if eq .values.secret.type "kubernetes.io/ssh-auth"}}
    type: kubernetes.io/ssh-auth
    data:
      ssh-privatekey: {{b64enc .values.secret.sshPrivatekey}}
    {{- else if eq .values.secret.type "kubernetes.io/tls"}}
    type: kubernetes.io/tls
    data:
      tls.key: {{b64enc .values.secret.key}}
      tls.crt: {{b64enc .values.secret.crt}}
    {{- end}}
  valueschema:
    properties:
      secret:
        anyOf:
        - properties:
            data:
              items:
                properties:
                  key:
                    maxLength: 253
                    pattern: ^[-._a-zA-Z0-9]+$
                    type: string
                  value:
                    format: textarea
                    type: string
                type: object
              type: array
            type:
              enum:
              - Opaque
              type: string
          title: Opaque
        - properties:
            password:
              type: string
            server:
              default: https://index.docker.io/v1/
              format: uri
              pattern: ^https://
              type: string
            type:
              enum:
              - kubernetes.io/dockerconfigjson
              type: string
            username:
              type: string
          title: kubernetes.io/dockerconfigjson
        - properties:
            password:
              type: string
            type:
              enum:
              - kubernetes.io/basic-auth
              type: string
            username:
              type: string
          title: kubernetes.io/basic-auth
        - properties:
            sshPrivatekey:
              format: ssh-private
              type: string
            type:
              enum:
              - kubernetes.io/ssh-auth
              type: string
          title: kubernetes.io/ssh-auth
        - properties:
            crt:
              format: ssh-cert
              type: string
            key:
              format: ssh-private
              type: string
            type:
              enum:
              - kubernetes.io/tls
              type: string
          title: kubernetes.io/tls
    type: object

