kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-observer
  labels:
    app: keycloak-observer
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list, watch, update]
- apiGroups: [""]
  resources: [services]
  verbs: [get, list, watch]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, create, update]
