kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keycloak-observer
  labels:
    app: keycloak-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keycloak-observer
subjects:
- kind: ServiceAccount
  name: keycloak-observer
  namespace: acc-global
