apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-observer
  namespace: acc-global
  labels:
    app: keycloak-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-observer
  template:
    metadata:
      labels:
        app: keycloak-observer
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
      containers:
      - name: keycloak-observer
        image: "{{ base_registry_address }}:{{ base_registry_port }}/keycloak-observer:{{ keycloak_observer_version }}"
        imagePullPolicy: Always
        command:
        - keycloak-observer
        - --keycloak-secret=acc-global/keycloak
        - --keycloak-service=acc-global/keycloak
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
      imagePullSecrets:
      - name: infra-registry
      serviceAccountName: keycloak-observer
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      volumes:
      - name: timezone
        hostPath:
          path: /etc/localtime
