kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alert-server
  labels:
    app: alert-server
rules:
- apiGroups: [""]
  resources: [secrets, configmaps]
  verbs: [get, list, watch, update]
- apiGroups: [monitoring.coreos.com]
  resources: [prometheusrules]
  verbs: [get, list, watch, update]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, create, update]
