apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alert-server
  namespace: acc-system
  labels:
    app: alert-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: accordion-storage
