apiVersion: v1
kind: Service
metadata:
  name: alert-server
  namespace: acc-system
  labels:
    app: alert-server
spec:
  selector:
    app: alert-server
  ports:
  - name: webhook
    port: 8080
    targetPort: 8080
    protocol: TCP
