apiVersion: v1
kind: Service
metadata:
  name: thanos-store-gateway
  namespace: acc-system
spec:
  type: NodePort
  ports:
    - name: grpc
      nodePort: 30002
      port: 10901
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: object-store-gateway
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: thanos-store

