---
###############################################################################
# scouter-manager
###############################################################################
- name: scouter-manager addon directory
  file: path={{ kube_addon_dir }}/acc-system/scouter-manager/cert state=directory owner={{ ansible_user }} group={{ ansible_group }}
  ignore_errors: yes

###############################################################################
- name: Copy tls.conf
  template:
    src: "scouter-manager/cert/{{ item }}"
    dest: "{{ kube_addon_dir }}/acc-system/scouter-manager/cert/{{ item }}"
  with_items:
    - tls.conf

- name: Create tls.key
  shell: >
    openssl genrsa -out {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.key 2048

- name: Create tls.csr
  shell: >
    openssl req -new -key {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.key -subj "/CN=mantech" -out {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.csr -config {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.conf

- name: Create tls.crt
  shell: >
    openssl x509 -req -in {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.csr -CA {{ kube_addon_dir }}/clusterinfo/cert/ca.crt -CAkey {{ kube_addon_dir }}/clusterinfo/cert/ca.key -CAcreateserial -out {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.crt -days {{ certificates_duration }} -extensions v3_req -extfile {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.conf

- name: Get ca.crt
  shell: >
    cat {{ kube_addon_dir }}/clusterinfo/cert/ca.crt
  register: scouter_ca_crt

- name: Base64 scouter_ca_crt
  shell: >
    echo {{ scouter_ca_crt.stdout | b64encode }}
  register: base64_scouter_ca_crt

- name: set var fact
  set_fact:
    base_scouter_ca_crt: "{{ base64_scouter_ca_crt }}"

- name: Get tls.crt
  shell: >
    cat {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.crt
  register: scouter_tls_crt

- name: Base64 scouter_tls_crt
  shell: >
    echo {{ scouter_tls_crt.stdout | b64encode }}
  register: base64_scouter_tls_crt

- name: set var fact
  set_fact:
    base_scouter_tls_crt: "{{ base64_scouter_tls_crt }}"

- name: Get tls.key
  shell: >
    cat {{ kube_addon_dir }}/acc-system/scouter-manager/cert/tls.key
  register: scouter_tls_key

- name: Base64 scouter_tls_key
  shell: >
    echo {{ scouter_tls_key.stdout | b64encode }}
  register: base64_scouter_tls_key

- name: set var fact
  set_fact:
    base_scouter_tls_key: "{{ base64_scouter_tls_key }}"

#################################################################################

- name: Copy files
  template:
    src: "scouter-manager/{{ item }}"
    dest: "{{ kube_addon_dir }}/acc-system/scouter-manager/{{ item }}"
  with_items:
    - scouter-manager-clusterrolebinding.yaml
    - scouter-manager-clusterrole.yaml
    - scouter-manager-cm.yaml
    - scouter-manager-deploy.yaml
    - scouter-manager-mutatingwebhook.yaml
    - scouter-manager-sa.yaml
    - scouter-manager-secret.yaml
    - scouter-manager-svc.yaml

- name: Deploy scouter-manager setup
  shell: >
    kubectl apply -f {{ kube_addon_dir }}/acc-system/scouter-manager
