apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alertmanager
    release: acc
  name: alertmanager
  namespace: acc-system
spec:
  endpoints:
  - interval: 30s
    port: web
  - interval: 30s
    port: reloader-web    
  selector:
    matchLabels:
      alertmanager: main
      release: acc

