apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-prometheus
subjects:
- kind: ServiceAccount
  name: prometheus-operator-prometheus
  namespace: acc-system
