apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-operator-prometheus-config
  namespace: acc-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
