---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scouter-manager
  labels:
    app: scouter-manager
rules:
- apiGroups: [""]
  resources: [namespaces, secrets]
  verbs: [get, list, watch, update]
- apiGroups: [""]
  resources: [serviceaccounts, services, persistentvolumeclaims, configmaps]
  verbs: [get, list, watch, create]
- apiGroups: [apps]
  resources: [deployments, statefulsets]
  verbs: ["*"]
- apiGroups: [monitoring.coreos.com]
  resources: [prometheusrules]
  verbs: [get, list, watch, delete]
- apiGroups: [monitoring.coreos.com]
  resources: [servicemonitors]
  verbs: [get, list, watch, create, delete]
- apiGroups: [""]
  resources: [events]
  verbs: [create]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, create, update]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scouter-server
  labels:
    app: scouter-server
rules:
- apiGroups: [policy]
  resources: [podsecuritypolicies]
  verbs: [use]
  resourceNames: [scouter-server]
