apiVersion: v1
kind: Service
metadata:
  name: scouter-manager
  namespace: acc-system
  labels:
    app: scouter-manager
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: scouter-manager
