---
apiVersion: v1
kind: Secret
metadata:
  name: scouter-manager
  namespace: acc-system
  labels:
    app: scouter-manager
type: kubernetes.io/tls
data:
  tls.crt: "{{ base_scouter_tls_crt.stdout }}"
  tls.key: "{{ base_scouter_tls_key.stdout }}"

