apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    release-name: filebeat
    release-namespace: acc-system
  labels:
    app: filebeat-filebeat
    release: filebeat
  name: filebeat-filebeat
  namespace: acc-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: filebeat-filebeat
      release: filebeat
  template:
    metadata:
      annotations:
        configChecksum: 0b65e7b122222585777781cd2b4aea9585b9302ced8260a932d40bddc9707a6
      labels:
        app: filebeat-filebeat
        release: filebeat
      name: filebeat-filebeat
    spec:
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
      - args:
        - -e
        - -E
        - http.enabled=true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: {{ base_registry_address }}:{{ base_registry_port }}/filebeat-oss:7.16.2-SNAPSHOT
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail 127.0.0.1:5066
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: filebeat
        securityContext:
          privileged: false
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/filebeat/filebeat.yml
          name: filebeat-config
          readOnly: true
          subPath: filebeat.yml
        - mountPath: /usr/share/filebeat/data
          name: data
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/log
          name: varlog
          readOnly: true
        - mountPath: /var/run/docker.sock
          name: varrundockersock
          readOnly: true
        - name: timezone
          mountPath: /etc/localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: filebeat-filebeat
      serviceAccountName: filebeat-filebeat
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: accordion-role
        value: infra
      volumes:
      - configMap:
          defaultMode: 384
          name: filebeat-filebeat-config
        name: filebeat-config
      - hostPath:
          path: /var/lib/filebeat-filebeat-elastic-data
          type: DirectoryOrCreate
        name: data
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: varrundockersock
      - name: timezone
        hostPath:
          path: /etc/localtime
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
