---
apiVersion: v1
kind: Service
metadata:
  annotations:
    release-name: logstash
    release-namespace: acc-system
  labels:
    app: logstash-logstash
    release: logstash
  name: logstash-logstash
  namespace: acc-system
spec:
  clusterIP: {{ service_ip.stdout }}.1.19
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    app: logstash-logstash
    chart: logstash
    release: logstash
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    release-name: logstash
    release-namespace: acc-system
  labels:
    app: logstash-logstash
    release: logstash
  name: logstash-logstash-headless
  namespace: acc-system
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9600
    protocol: TCP
    targetPort: 9600
  selector:
    app: logstash-logstash
  sessionAffinity: None
  type: ClusterIP

