apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    release-name: logstash
    release-namespace: acc-system
  labels:
    app: logstash-logstash
    release: logstash
  name: logstash-logstash-config
  namespace: acc-system
data:
  logstash.yml: |
    http.host: 0.0.0.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    release-name: logstash
    release-namespace: acc-system
  labels:
    app: logstash-logstash
    release: logstash
  name: logstash-logstash-pipeline
  namespace: acc-system
data:
  logstash.conf: "input {\n  beats {\n    port => 5044\n  }\n}\noutput { \n if [service]
    == \"audit\" { opensearch { \n    hosts => [\"opensearch-cluster-master.acc-system:9200\"] \n
    \   manage_template => false\n index => \"acc-audit-%{+YYYY.MM.dd}\"\n  }\n}\n
    else { opensearch { \n    hosts => [\"opensearch-cluster-master.acc-system:9200\"] \n    manage_template
    => false\n index => \"acc-log-%{+YYYY.MM.dd}\"\n  }\n}\n }"
