apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    majorVersion: "2"
  labels:
    helm.sh/chart: opensearch-2.6.2
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
    app.kubernetes.io/version: "2.3.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: opensearch-cluster-master
  name: opensearch-cluster-master
  namespace: acc-system
spec:
  podManagementPolicy: Parallel
{% if elasticsearch_ha == "yes" %}
  replicas: 3
{% else %}
  replicas: 1
{% endif %}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/instance: opensearch
  serviceName: opensearch-cluster-master-headless
  template:
    metadata:
      annotations:
        configchecksum: c00d75aa84c92e9846cdd059ab45903d9f6dff1c65fa6dbaf408a3c931bb3f8
      labels:
        helm.sh/chart: opensearch-2.6.2
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/instance: opensearch
        app.kubernetes.io/version: "2.3.0"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: opensearch-cluster-master
      name: opensearch-cluster-master
    spec:
{% if elasticsearch_ha == "yes" %}
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: elasticsearch-master
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
{% endif %}
      imagePullSecrets:
      - name: infra-registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: accordion-role
                operator: In
                values:
                - infra
            weight: 100
      tolerations:
      - effect: NoSchedule
        key: accordion-role
        operator: Equal
        value: infra
      containers:
      - env:
        - name: node.name
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
{% if elasticsearch_ha == "yes" %}
        - name: cluster.initial_master_nodes
          value: opensearch-cluster-master-0, opensearch-cluster-master-1, opensearch-cluster-master-2
{% else %}
        - name: discovery.type
          value: single-node
{% endif %}
        - name: discovery.seed_hosts
          value: opensearch-cluster-master-headless
        - name: cluster.name
          value: opensearch-cluster
        - name: network.host
          value: 0.0.0.0
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xmx2G -Xms2G
        - name: node.roles
          value: master,ingest,data,remote_cluster_client,
        image: {{ base_registry_address }}:{{ base_registry_port }}/opensearch:1.3.0
        imagePullPolicy: IfNotPresent
        name: opensearch
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-cluster-master
        - mountPath: /usr/share/opensearch/config/opensearch.yml
          name: config
          subPath: opensearch.yml
        - name: timezone
          mountPath: /etc/localtime
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - args:
        - chown -R 1000:1000 /usr/share/opensearch/data
        command:
        - sh
        - -c
        image: {{ base_registry_address }}:{{ base_registry_port }}/busybox:latest
        imagePullPolicy: Always
        name: fsgroup-volume
        resources: {}
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-cluster-master
        - name: timezone
          mountPath: /etc/localtime          
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: opensearch-cluster-master-config
        name: config
      - name: timezone
        hostPath:
          path: /etc/localtime
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: opensearch-cluster-master
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ elastic_storage }}
      volumeMode: Filesystem
      storageClassName: accordion-storage
