apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    generation: 1
    labels:
      app: logstash-logstash
      release: logstash
    name: logstash-logstash-pdb
    namespace: acc-system
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        app: logstash-logstash
  status:
    currentHealthy: 1
    desiredHealthy: 0
    disruptionsAllowed: 1
    expectedPods: 1
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
