apiVersion: v1
kind: Service
metadata:
  name: user-registry
  namespace: acc-system
  labels:
    app: user-registry
spec:
  clusterIP: {{ service_ip.stdout }}.1.11
  selector:
    app: user-registry
  type: NodePort
  ports:
  - name: registry
    port: 5000
    protocol: TCP
    nodePort: {{ user_registry_port }}

