kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: user-registry
  namespace: acc-system
  labels:
    app: user-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ registry_storage }}
  storageClassName: "accordion-storage"
  volumeMode: Filesystem

